<?php
$temp_layer = [
	'0' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#179299',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(23, 146, 153, 1)',
							'color2' => '',
							'transparency2' => '',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'color_filter' => '1',
							'overlay_color' => [
									'color' => '#000500',
									'transparency' => '0.90',
									'rgba' => 'rgba(0, 5, 0, 0.9)',
							],
							'efect' => '',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'custom',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'default',
					'min-height' => '100',
					'arrow_color' => '#fff',
					'content_align' => 'center',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '100',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '100',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '#ededed',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'show' => '1',
							'shape' => 'triangle_negative',
							'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,0V150L500,2,0,150V0H1000Z"></path></svg>',
							'size' => '54',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => 'rgb(255, 255, 255)',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-one',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '55',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '1',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<h1 style="text-align: center;">' . __('Objednávka', 'cms_ve') . '</h1>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
													'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.</p>',
													'li' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '600',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
	'1' => [
			'class' => '',
			'style' => [
					'font' => [
							'font-size' => '',
							'font-family' => '',
							'weight' => '',
							'color' => '',
					],
					'link_color' => '',
					'background_color' => [
							'color1' => '#ffffff',
							'color2' => '',
							'transparency1' => '1',
							'rgba1' => 'rgba(255, 255, 255, 1)',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_image' => [
							'position' => '50% 50%',
							'repeat' => 'no-repeat',
							'image' => '',
							'efect' => '',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.5',
									'rgba' => 'rgba(0,0,0,0.5)',
							],
							'cover' => '1',
					],
					'border-top' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'padding_top' => '100',
					'padding_bottom' => '100',
					'video_type' => 'custom',
					'content_align' => 'top',
					'row_height' => '',
					'text' => 'auto',
					'row_padding' => 'big',
					'margin_top' => '',
					'margin_bottom' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-twothree',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'bullets',
											'style' => [
													'bullets' => [
															'0' => [
																	'title' => 'Lorem ipsum dolor',
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
															],
															'1' => [
																	'title' => 'Sed pulvinar lacus ',
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
															],
															'2' => [
																	'title' => 'Proin dui lacus',
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
															],
													],
													'type' => 'decimal',
													'style' => '2',
													'start_number' => '1',
													'bullet_icon' => [
															'icon' => 'right1',
															'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/content-icons.svg#icon-right1"></use></svg>',
															'tab' => 'icon',
													],
													'custom_image' => [
															'position' => '',
															'image' => '',
															'imageid' => '',
													],
													'size' => '22',
													'space' => '30',
													'bullet_color' => '#179299',
													'title_font' => [
															'use-font' => 'subtitle',
															'font-size' => '22',
															'color' => '',
													],
													'text_font' => [
															'font-size' => '',
															'color' => '',
													],
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '68',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'fapi',
											'style' => [
													'form-style' => '1',
													'background-color' => '#ffffff',
													'font_title' => [
															'font-size' => '19',
															'font-family' => '',
															'weight' => '',
															'color' => '',
													],
													'font_text' => [
															'font-size' => '14',
													],
													'button' => [
															'style' => 'basic',
															'button_size' => 'medium',
															'custom_size' => '18',
													],
													'mw30' => '1',
													'content' => '',
											],
											'config' => [
													'max_width' => '',
													'margin_top' => '0',
													'margin_bottom' => '25',
													'delay' => '',
													'class' => '',
											],
									],
							],
					],
					'1' => [
							'type' => 'col-three',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'graphic',
											'style' => [
													'type' => 'img',
													'graphic_hr' => '1',
													'border' => [
															'size' => '',
															'style' => 'solid',
															'color' => '',
															'transparency' => '0.2',
															'rgba' => '',
													],
													'hr_color' => 'auto',
													'graphic_img' => 'guarantee6',
													'graphic_mockups' => '1',
													'mockup_image' => [
															'position' => '50% 50%',
															'image' => '',
															'imageid' => '',
													],
													'click_action' => 'none',
													'popup' => '',
													'link' => [
															'page' => '',
															'link' => '',
													],
													'graphic_book' => '1',
													'book_title' => __('NÁZEV KNIHY', 'cms_ve'),
													'book_author' => __('Jméno Příjmení', 'cms_ve'),
													'content_align' => 'left',
													'title_font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '60',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'line-height' => '1.1',
													],
													'author_font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '17',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
													],
													'book_background_color' => '#6599a3',
													'book_background_image' => [
															'position' => '10% 50%',
															'image' => MW_IMAGE_LIBRARY . 'bg/coast.jpeg',
															'imageid' => '',
															'cover' => '1',
															'overlay_color' => [
																	'color' => '#000000',
																	'transparency' => '0.2',
																	'rgba' => 'rgba(0, 0, 0, 0.2)',
															],
															'repeat' => 'no-repeat',
															'size' => '',
													],
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '211',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '22',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '3',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<p style="text-align: center;">' . __('30 dní garance vrácení peněz', 'cms_ve') . '</p>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '15',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'2' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '',
															'font-family' => '',
															'weight' => '',
															'color' => '',
													],
													'li' => '0',
													'mw30' => '1',
													'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus.</p>',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
											],
									],
									'3' => [
											'type' => 'testimonials',
											'style' => [
													'testimonials' => [
															'0' => [
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. ',
																	'name' => __('Jan Novák', 'cms_ve'),
																	'company' => 'Grafik',
																	'image' => [
																			'position' => '',
																			'image' => MW_IMAGE_LIBRARY . 'misc/face-m.jpg',
																			'imageid' => '',
																	],
															],
															'1' => [
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. ',
																	'name' => __('Jan Novák', 'cms_ve'),
																	'company' => 'Grafik',
																	'image' => [
																			'position' => '',
																			'image' => MW_IMAGE_LIBRARY . 'misc/face-m.jpg',
																			'imageid' => '',
																	],
															],
													],
													'cols' => 'one',
													'style' => '9',
													'background_set' => [
															'corner' => '2',
															'shadow' => '2',
															'border' => '1',
													],
													'font' => [
															'font-size' => '15',
															'color' => '',
													],
													'font-author' => [
															'font-size' => '',
															'color' => '',
													],
													'miocarousel_setting' => [
															'animation' => 'fade',
															'color_scheme' => '',
															'delay' => '3500',
															'speed' => '1000',
													],
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
	'2' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#212121',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(33, 33, 33, 1)',
							'color2' => '',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.5',
									'rgba' => 'rgba(0,0,0,0.5)',
							],
							'efect' => '',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'custom',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'default',
					'min-height' => '100',
					'arrow_color' => '#fff',
					'content_align' => 'top',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '100',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '100',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-one',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '24',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '3',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<p style="text-align: center;">' . __('Potřebujete pomoc?', 'cms_ve') . '</p>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '',
															'font-family' => '',
															'weight' => '',
															'color' => '',
													],
													'li' => '',
													'mw30' => '1',
													'content' => '<p style="text-align: center;">' . __('Napište mi na <a href="">mujmail@seznam.cz</a> nebo volejte na 123 456 789.', 'cms_ve') . '</p>',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232,232,232,1)',
													],
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
];

$page = [
	'page' => [
		'title' => __('Objednávka', 'cms_ve'),
		'slug' => __('objednavka', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'none',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
