<?php
$temp_layer = [
	'0' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#ffffff',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(255, 255, 255, 1)',
							'color2' => '',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'color_filter' => '1',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.85',
									'rgba' => 'rgba(0, 0, 0, 0.85)',
							],
							'efect' => 'parallax',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'iframe',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'default',
					'min-height' => '100',
					'arrow_color' => '#fff',
					'content_align' => 'center',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '50',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '50',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'show' => '1',
							'shape' => 'triangle_negative',
							'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,0V150L500,2,0,150V0H1000Z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => 'rgb(23, 146, 153)',
							'flip' => '1',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-one',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '45',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '1',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#efefef',
															'transparency1' => '',
															'rgba1' => '',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<h1 style="text-align: center;">' . __('Krok 1: Stáhněte si svůj e-book', 'cms_ve') . '</h1>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '515',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232, 232, 232, 1)',
													],
													'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem.</p>',
													'li' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '40',
													'max_width' => '492',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'2' => [
											'type' => 'button',
											'style' => [
													'content' => __('Stáhnout e-book!', 'cms_ve'),
													'subtext' => '',
													'align' => 'center',
													'show' => 'url',
													'link' => [
															'page' => '',
															'link' => '',
													],
													'popup' => '',
													'button_style' => [
															'style' => 'basic',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '8',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'big',
															'custom_size' => '18',
													],
													'icon' => [
															'icon' => 'download',
															'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
															'icon_set' => 'feather',
															'tab' => 'icon',
													],
													'icon_size' => '1.1',
													'icon_align' => 'left',
													'text2' => __('Text tlačítka', 'cms_ve'),
													'subtext2' => '',
													'show2' => 'url',
													'link2' => [
															'page' => '',
															'link' => '',
													],
													'popup2' => '',
													'button_style2' => [
															'style' => 'basic',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '8',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'medium',
															'custom_size' => '18',
													],
													'icon2' => [
															'icon' => 'download',
															'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
															'icon_set' => 'feather',
															'tab' => 'icon',
													],
													'icon_size2' => '1.1',
													'icon_align2' => 'left',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '20',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'3' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '13',
															'color' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232, 232, 232, 1)',
													],
													'content' => '<p style="text-align: center;">' . __('Je něco v nepořádku? <a href="">Kontaktujte nás</a>.', 'cms_ve') . '</p>',
													'li' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '600',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
	'1' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#179299',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(23, 146, 153, 1)',
							'color2' => '',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'color_filter' => '1',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.85',
									'rgba' => 'rgba(0, 0, 0, 0.85)',
							],
							'efect' => 'parallax',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'iframe',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'default',
					'min-height' => '100',
					'arrow_color' => '#fff',
					'content_align' => 'center',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '50',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '50',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'shape' => 'ramp',
							'code' => '<svg preserveAspectRatio="none" viewBox="0 0 1000 150"><path d="M0,0V2S216.952-1.19,475,34c287.9,39.262,525,116,525,116V0H0Z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
							'flip' => '1',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-one',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '45',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '1',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#efefef',
															'transparency1' => '',
															'rgba1' => '',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<h1 style="text-align: center;">' . __('Krok 2: Začněte budovat své publikum', 'cms_ve') . '</h1>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '515',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232, 232, 232, 1)',
													],
													'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem.</p>',
													'li' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '40',
													'max_width' => '492',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'2' => [
											'type' => 'button',
											'style' => [
													'content' => __('Chci vědět více', 'cms_ve'),
													'subtext' => '',
													'align' => 'center',
													'show' => 'url',
													'link' => [
															'page' => $installed['sale'],
															'link' => '',
													],
													'popup' => '',
													'button_style' => [
															'style' => 'basic',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '8',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'big',
															'custom_size' => '18',
													],
													'icon' => [
															'icon' => 'download',
															'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
															'icon_set' => 'feather',
															'tab' => 'icon',
													],
													'icon_size' => '1.1',
													'icon_align' => 'left',
													'text2' => __('Text tlačítka', 'cms_ve'),
													'subtext2' => '',
													'show2' => 'url',
													'link2' => [
															'page' => '',
															'link' => '',
													],
													'popup2' => '',
													'button_style2' => [
															'style' => 'basic',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '8',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'medium',
															'custom_size' => '18',
													],
													'icon2' => [
															'icon' => 'download',
															'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
															'icon_set' => 'feather',
															'tab' => 'icon',
													],
													'icon_size2' => '1.1',
													'icon_align2' => 'left',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
];
$page = [
	'page' => [
		'title' => __('Poděkování po registraci', 'cms_ve'),
		'slug' => __('dekuji', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'none',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
