<?php
$temp_layer = [
	'0' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#ffffff',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(255, 255, 255, 1)',
							'color2' => '',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'color_filter' => '1',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.85',
									'rgba' => 'rgba(0, 0, 0, 0.85)',
							],
							'efect' => 'parallax',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'iframe',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'full',
					'min-height' => '100',
					'arrow_color' => '#fff',
					'content_align' => 'center',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '50',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '50',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '',
							'style' => 'solid',
							'color' => '',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'shape' => 'ramp',
							'code' => '<svg preserveAspectRatio="none" viewBox="0 0 1000 150"><path d="M0,0V2S216.952-1.19,475,34c287.9,39.262,525,116,525,116V0H0Z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
							'flip' => '1',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-two',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-size' => '17',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '#179299',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '',
															'transparency1' => '1',
															'rgba1' => '',
													],
													'content' => '<p style="text-align: center;">LIMITOVANÁ NABÍDKA</p>',
													'li' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '0',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'1' => [
											'type' => 'title',
											'style' => [
													'font' => [
															'font-size' => '50',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'font-family' => '',
															'weight' => '',
															'line-height' => '',
															'letter-spacing' => '',
															'text-shadow' => 'none',
													],
													'style' => '1',
													'border' => [
															'size' => '1',
															'style' => 'solid',
															'color' => '#d5d5d5',
													],
													'background-color' => [
															'color1' => '#efefef',
															'transparency1' => '',
															'rgba1' => '',
													],
													'decoration-color' => '#158ebf',
													'decoration-padding' => '',
													'align' => 'center',
													'content' => '<h1 style="text-align: center;">' . __('Název magnetu ke stažení zdarma', 'cms_ve') . '</h1>',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'2' => [
											'type' => 'text',
											'style' => [
													'font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '',
															'color' => '',
															'line-height' => '',
													],
													'style' => '1',
													'p-background-color' => [
															'color1' => '#e8e8e8',
															'transparency1' => '1',
															'rgba1' => 'rgba(232, 232, 232, 1)',
													],
													'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem.</p>',
													'li' => '',
											],
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '40',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'3' => [
											'type' => 'seform',
											'style' => [
													'type' => 'smartemailing',
													'content' => [
															'api' => 'se',
													],
													'email' => '',
													'subject' => '',
													'button_text' => __('Stáhnout', 'cms_ve'),
													'thx_url' => [
															'page' => '',
															'link' => '',
													],
													'url' => '',
													'form-style' => '1',
													'form-labels' => '1',
													'form-look' => '3',
													'background' => '#eeeeee',
													'corners' => 'rounded',
													'form-font' => [
															'font-size' => '15',
													],
													'button' => [
															'style' => 'basic',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '9999',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'medium',
															'custom_size' => '18',
													],
													'popup_type' => 'button',
													'image' => [
															'position' => '',
															'image' => '',
															'imageid' => '',
													],
													'popup_text' => __('Stáhnout ebook', 'cms_ve'),
													'popupbutton' => [
															'style' => '2',
															'custom_setting' => [
																	'style' => '1',
																	'background_color' => [
																			'color1' => '#eb1e47',
																			'transparency1' => '1',
																			'rgba1' => 'rgba(235, 30, 71, 1)',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'font-color' => '',
																	'corner' => '9999',
																	'height_padding' => '1.1',
																	'width_padding' => '1.8',
																	'font' => [
																			'font-family' => '',
																			'weight' => '',
																	],
																	'border-color' => '',
																	'border_width' => '',
																	'hover_effect' => 'darker',
																	'hover_color' => [
																			'color1' => '',
																			'transparency1' => '1',
																			'rgba1' => '',
																			'color2' => '',
																			'transparency2' => '1',
																			'rgba2' => '',
																	],
																	'hover_font_color' => '',
																	'border_hover-color' => '',
															],
															'button_size' => 'medium',
															'custom_size' => '18',
													],
													'link_text' => __('Registrovat se', 'cms_ve'),
													'link_font' => [
															'font-size' => '',
															'color' => '',
													],
													'align' => 'left',
													'popup_title' => __('Zadejte svůj e-mail a stáhněte si e-book.', 'cms_ve'),
													'textinpopup' => '',
													'mw30' => '1',
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '381',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
									'4' => [
											'style' => [
													'content' => [
															'page' => '',
															'link' => '',
													],
													'layout' => 'button',
													'scheme' => 'light',
													'setting' => [
															'share' => '1',
															'is_saved' => '1',
													],
													'align' => 'center',
													'mw30' => '1',
											],
											'type' => 'like',
											'config' => [
													'margin_top' => '',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
					'1' => [
							'type' => 'col-two',
							'class' => '',
							'content' => [
									'0' => [
											'style' => [
													'type' => 'mockups',
													'graphic_hr' => '1',
													'border' => [
															'size' => '',
															'style' => 'solid',
															'color' => '',
															'transparency' => '0.2',
															'rgba' => '',
													],
													'hr_color' => 'auto',
													'graphic_img' => 'guarantee2',
													'graphic_mockups' => '3',
													'mockup_image' => [
															'position' => '50% 50%',
															'image' => MW_IMAGE_LIBRARY . 'bg/man_with_comp.jpg',
															'imageid' => '',
													],
													'click_action' => 'none',
													'popup' => '',
													'link' => [
															'page' => '',
															'link' => '',
													],
													'graphic_book' => '1',
													'book_title' => __('NÁZEV KNIHY', 'cms_ve'),
													'book_author' => __('Jméno Příjmení', 'cms_ve'),
													'content_align' => 'left',
													'title_font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '60',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
															'line-height' => '1.1',
													],
													'author_font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '17',
															'tablet' => [
																	'font-size' => '',
															],
															'mobile' => [
																	'font-size' => '',
															],
															'color' => '',
													],
													'book_background_color' => '#6599a3',
													'book_background_image' => [
															'position' => '10% 50%',
															'image' => MW_IMAGE_LIBRARY . 'bg/coast2.jpg',
															'imageid' => '',
															'cover' => '1',
															'color_filter' => '1',
															'overlay_color' => [
																	'color' => '#000000',
																	'transparency' => '0.2',
																	'rgba' => 'rgba(0, 0, 0, 0.2)',
															],
															'repeat' => 'no-repeat',
															'size' => '',
													],
													'mw30' => '1',
											],
											'type' => 'graphic',
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
	'1' => [
			'class' => '',
			'style' => [
					'background_color' => [
							'color1' => '#f2f2f2',
							'transparency1' => '1.00',
							'rgba1' => 'rgba(242, 242, 242, 1)',
							'color2' => '',
							'transparency2' => '1',
							'rgba2' => '',
					],
					'background_setting' => 'image',
					'background_image' => [
							'position' => 'center center',
							'image' => '',
							'imageid' => '',
							'pattern' => '',
							'tablet' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'mobile' => [
									'position' => '50% 50%',
									'image' => '',
									'imageid' => '',
									'size' => '',
							],
							'cover' => '1',
							'overlay_color' => [
									'color' => '#000000',
									'transparency' => '0.70',
									'rgba' => 'rgba(0, 0, 0, 0.70)',
							],
							'efect' => '',
							'repeat' => 'no-repeat',
							'size' => '',
					],
					'slider_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'video_type' => 'iframe',
					'video_url' => '',
					'background_video_mp4' => '',
					'background_video_webm' => '',
					'background_video_ogg' => '',
					'video_image' => [
							'position' => '50% 50%',
							'image' => '',
							'imageid' => '',
							'cover' => '1',
							'size' => '',
					],
					'video_overlay_color' => [
							'color' => '',
							'transparency' => '0.7',
							'rgba' => '',
					],
					'row_height' => 'default',
					'min-height' => '',
					'arrow_color' => '#fff',
					'content_align' => 'top',
					'text' => 'auto',
					'font' => [
							'font-family' => '',
							'weight' => '',
							'font-size' => '',
							'color' => '',
					],
					'link_color' => '',
					'type' => 'basic',
					'row_padding' => 'big',
					'padding_top' => '100',
					'tablet' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'mobile' => [
							'padding_top' => '',
							'padding_bottom' => '',
							'padding_left' => [
									'size' => '',
									'unit' => 'px',
							],
							'padding_right' => [
									'size' => '',
									'unit' => 'px',
							],
					],
					'padding_bottom' => '100',
					'padding_left' => [
							'size' => '',
							'unit' => 'px',
					],
					'padding_right' => [
							'size' => '',
							'unit' => 'px',
					],
					'border-top' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'border-bottom' => [
							'size' => '0',
							'style' => 'solid',
							'color' => '',
					],
					'shape_top' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'shape_bottom' => [
							'shape' => 'tilt',
							'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
							'size' => '100',
							'tablet' => [
									'size' => '',
							],
							'mobile' => [
									'size' => '',
							],
							'color' => '',
					],
					'margin_top' => '',
					'margin_bottom' => '',
					'css_class' => '',
					'row_anchor' => '',
					'delay' => '',
			],
			'content' => [
					'0' => [
							'type' => 'col-one',
							'class' => '',
							'content' => [
									'0' => [
											'type' => 'testimonials',
											'style' => [
													'testimonials' => [
															'0' => [
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
																	'name' => __('Petra', 'cms_ve'),
																	'company' => __('Finanční poradce', 'cms_ve'),
																	'image' => [
																			'position' => '',
																			'image' => MW_IMAGE_LIBRARY . 'misc/face-w.jpg',
																			'imageid' => '',
																	],
															],
															'1' => [
																	'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
																	'name' => __('Honza', 'cms_ve'),
																	'company' => __('Informatik', 'cms_ve'),
																	'image' => [
																			'position' => '',
																			'image' => MW_IMAGE_LIBRARY . 'misc/face-m.jpg',
																			'imageid' => '',
																	],
															],
													],
													'cols' => 'two',
													'style' => '6',
													'font' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '',
															'color' => '',
															'line-height' => '',
													],
													'font-author' => [
															'font-family' => '',
															'weight' => '',
															'font-size' => '',
															'color' => '',
													],
													'miocarousel_setting' => [
															'animation' => 'fade',
															'color_scheme' => '',
															'delay' => '3500',
															'speed' => '1000',
													],
											],
											'config' => [
													'margin_top' => '0',
													'tablet' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'mobile' => [
															'margin_top' => '',
															'margin_bottom' => '',
															'max_width' => '',
													],
													'margin_bottom' => '',
													'max_width' => '',
													'element_align' => 'center',
													'animate' => '',
													'id' => '',
													'class' => '',
													'delay' => '',
											],
									],
							],
					],
			],
			'type' => 'basic',
	],
];

$page = [
	'page' => [
		'title' => __('Vstupní', 'cms_ve'),
		'slug' => __('vstup', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'none',
		],
		've_footer' => [
			'show' => 'page',
			'custom_footer' => '',
			'appearance' => 'type2',
			'text' => '',
			'menu' => '',
			'background_color' => [
					'color1' => '#f2f2f2',
					'transparency1' => '1.00',
					'rgba1' => 'rgba(242, 242, 242, 1)',
					'color2' => '',
					'transparency2' => '1',
					'rgba2' => '',
			],
			'font' => [
					'font-family' => '',
					'weight' => '',
					'font-size' => '14',
					'color' => '#7a7a7a',
			],
			'background_image' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'overlay_color' => [
							'color' => '#158ebf',
							'transparency' => '1',
							'rgba' => '',
					],
					'repeat' => 'no-repeat',
					'size' => '',
			],
			'footer_width_preset' => '',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
