<?php
$temp_layer = [
	'0' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1',
				'rgba1' => 'rgba(255, 255, 255, 1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => 'center center',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'color_filter' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.5',
					'rgba' => 'rgba(0,0,0,0.5)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'iframe',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '',
			'arrow_color' => '#fff',
			'content_align' => 'top',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'custom',
			'padding_top' => '0',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '90',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'show' => '1',
				'shape' => 'zigzag',
				'code' => '<svg viewBox="0.5 0.5 1800 5.8">
      <path d="M5.4.4l5.4 5.3L16.5.4l5.4 5.3L27.5.4 33 5.7 38.6.4l5.5 5.4h.1L49.9.4l5.4 5.3L60.9.4l5.5 5.3L72 .4l5.5 5.3L83.1.4l5.4 5.3L94.1.4l5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.4 5.3L161 .4l5.4 5.3L172 .4l5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3L261 .4l5.4 5.3L272 .4l5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3L361 .4l5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.6-5.4 5.5 5.3L461 .4l5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1L550 .4l5.4 5.3L561 .4l5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2L650 .4l5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2L750 .4l5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.4h.2L850 .4l5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.4h.2l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.7-5.4 5.4 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.5 5.4h.1l5.6-5.4 5.5 5.3 5.6-5.3 5.5 5.3 5.6-5.3 5.4 5.3 5.7-5.3 5.4 5.3 5.6-5.3 5.5 5.4V0H-.2v5.8z"></path>
    </svg>',
				'size' => '10',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
				'flip' => '1',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'break' => '1',
				'content' => [
					'0' => [
						'style' => [
							'show_info' => '1',
							'show_play' => '1',
							'style' => '6',
							'background-color' => '#f2f2f2',
							'color-active' => '#179299',
							'font' => [
								'font-size' => '',
								'color' => '',
							],
							'mw30' => '1',
						],
						'type' => 'funnel_nav',
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '17',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'1' => [
				'type' => 'col-twothree',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'content' => '',
							'popup_type' => 'image',
							'play' => [
								'icon' => 'play1',
								'size' => '60',
								'color' => '#ffffff',
							],
							'button_text' => __('Spustit video', 'cms_ve'),
							'mw30' => '1',
						],
						'type' => 'video',
					],
				],
			],
			'2' => [
				'type' => 'col-three',
				'class' => '',
				'content' => [
					'0' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '23',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#efefef',
								'transparency1' => '1',
								'rgba1' => '',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p>' . __('Nadpis lekce', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'text',
						'style' => [
							'font' => [
								'font-family' => '',
								'weight' => '',
								'font-size' => '',
								'color' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '',
								'transparency1' => '1',
								'rgba1' => '',
							],
							'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac dolor at leo feugiat convallis. Donec congue porttitor scelerisque. Donec congue porttitor scelerisque.</p>',
							'li' => '',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '25',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'content' => [
								'0' => [
									'name' => __('Stáhnout ebook', 'cms_ve'),
									'file' => '',
									'desc' => '',
									'icon' => [
										'icon' => 'download',
										'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
										'icon_set' => 'feather',
										'tab' => 'icon',
									],
								],
								'1' => [
									'name' => __('Stáhnout mp3', 'cms_ve'),
									'file' => '',
									'desc' => '',
									'icon' => [
										'icon' => 'download',
										'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-download"></use></svg>',
										'icon_set' => 'feather',
										'tab' => 'icon',
									],
								],
							],
							'style' => '3',
							'background_set' => [
								'corner' => '',
								'shadow' => '1',
								'color' => '#ffffff',
							],
							'icon_style' => '2',
							'color' => '#179299',
							'font' => [
								'font-size' => '14',
							],
							'mw30' => '1',
						],
						'type' => 'member_download',
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'3' => [
						'style' => [
							'content' => [
								'page' => '',
								'link' => '',
							],
							'appearance' => 'button',
							'button_text' => __('Sdílet na Facebooku', 'cms_ve'),
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '8',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'icon' => [
								'icon' => 'facebook1',
								'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/social-icons.svg#icon-facebook1"></use></svg>',
								'tab' => 'icon',
							],
							'layout' => 'button_count',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'align' => 'left',
							'mw30' => '1',
						],
						'type' => 'fac_share',
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
	'1' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#f2f2f2',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(242, 242, 242, 1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.2',
					'rgba' => 'rgba(0, 0, 0, 0.2)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'top',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '50',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '50',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-twothree',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-family' => '',
								'weight' => '',
								'font-size' => '',
								'color' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam.</p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '64',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '28',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#efefef',
								'transparency1' => '1',
								'rgba1' => 'rgba(239, 239, 239, 1)',
							],
							'decoration-color' => '#158ebf',
							'align' => 'center',
							'content' => '<h2>' . __('Přidejte se do diskuze', 'cms_ve') . '</h2>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '40',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'per_page' => '10',
							'scheme' => 'dark',
							'mw30' => '1',
						],
						'type' => 'fcomments',
					],
					'3' => [
						'style' => [
							'style' => '3',
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'mw30' => '1',
						],
						'type' => 'wpcomments',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'1' => [
				'type' => 'col-three',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'background_color' => [
								'color1' => '#ffffff',
								'transparency1' => '1.00',
								'rgba1' => 'rgba(255, 255, 255, 1)',
							],
							'background_image' => [
								'position' => '50% 50%',
								'image' => '',
								'imageid' => '',
								'pattern' => '0',
								'cover' => '1',
								'overlay_color' => [
									'color' => '#158ebf',
									'transparency' => '1',
									'rgba' => '',
								],
								'repeat' => 'no-repeat',
								'size' => '',
							],
							'border' => [
								'size' => '0',
								'style' => 'solid',
								'color' => '#eeeeee',
							],
							'corner' => '2',
							'padding' => [
								'size' => '40',
								'unit' => 'px',
							],
							'shadow' => '3',
							'text' => 'auto',
							'title' => '',
							'title_bg' => [
								'color1' => '',
								'transparency1' => '1',
								'rgba1' => '',
							],
							'title_border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#000000',
								'transparency' => '0.2',
								'rgba' => 'rgba(0,0,0,0.2)',
							],
							'title-font' => [
								'use-font' => 'title',
								'font-size' => '20',
								'color' => '',
								'align' => 'center',
							],
							'mw30' => '1',
						],
						'type' => 'box',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
						'content' => [
							'0' => [
								'0' => [
									'style' => [
										'peoples' => [
											'0' => [
												'title' => __('Jméno Příjmení', 'cms_ve'),
												'position' => __('Autor projektu', 'cms_ve'),
												'text' => '',
												'image' => [
													'position' => '50% 50%',
													'image' => '',
													'imageid' => '',
												],
												'link' => [
													'page' => '',
													'link' => '',
												],
												'facebook' => '',
												'linkedin' => '',
												'youtube' => '',
												'twitter' => '',
												'google' => '',
											],
										],
										'cols' => 'one',
										'cols_type' => 'cols',
										'style' => '1',
										'background_set' => [
											'corner' => '',
											'shadow' => '1',
											'color' => '#ffffff',
										],
										'hover_color' => [
											'color' => '#000000',
											'transparency' => '0.5',
											'rgba' => 'rgba(0,0,0,0.5)',
										],
										'image_size' => '2',
										'image_ratio' => 'original',
										'hover' => '',
										'icons_color' => '#ababab',
										'font' => [
											'use-font' => 'title',
											'font-size' => '18',
											'color' => '',
										],
										'font_position' => [
											'font-size' => '',
											'color' => '',
										],
										'font_text' => [
											'font-size' => '',
										],
										'mw30' => '1',
									],
									'type' => 'peoples',
									'config' => [
										'margin_top' => '0',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
								'1' => [
									'style' => [
										'font' => [
											'font-family' => '',
											'weight' => '',
											'font-size' => '',
											'color' => '',
											'line-height' => '',
										],
										'style' => '1',
										'p-background-color' => [
											'color1' => '#e8e8e8',
											'transparency1' => '1',
											'rgba1' => 'rgba(232,232,232,1)',
										],
										'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus.</p>',
										'li' => '',
										'mw30' => '1',
									],
									'type' => 'text',
									'config' => [
										'margin_top' => '0',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
							],
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
];
$page = [
	'page' => [
		'title' => __('Obsah 3', 'cms_ve'),
		'slug' => __('obsah3', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'page',
			'logo_setting' => 'image',
			'logo' => [
				'position' => '',
				'image' => MW_IMAGE_LIBRARY . 'logo/vaselogo2.png',
				'imageid' => '',
			],
			'logo_size' => '170',
			'logo_text' => __('Název webu', 'cms_ve'),
			'logo_font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '20',
				'color' => '#111111',
			],
			'appearance' => 'type11',
			'menu_style' => '1',
			'menu' => '',
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1',
				'rgba1' => 'rgba(255,255,255,1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'header_padding' => '20',
			'header_height' => '60',
			'menu_font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '15',
				'line-height' => '1.6',
			],
			'menu_color' => '#575757',
			'menu_active_color' => '#158ebf',
			'menu_submenu_bg' => '#ffffff',
			'menu_bg' => '#121212',
			'before_header' => '',
			'border-bottom' => [
				'size' => '',
				'style' => 'solid',
				'color' => '#eeeeee',
				'transparency' => '1',
				'rgba' => '',
			],
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'overlay_color' => [
					'color' => '#158ebf',
					'transparency' => '1',
					'rgba' => '',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'header_width_preset' => '',
			'background_color_fix' => [
				'color1' => '',
				'transparency1' => '1',
				'rgba1' => '',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'logo_color_fix' => '',
			'fixed_menu_color' => '',
			'fixed_menu_active_color' => '',
			'header_padding_fix' => '20',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
