<?php
$temp_layer = [
	'0' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(255, 255, 255, 1)',
				'color2' => '',
				'transparency2' => '',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'color_filter' => '1',
				'overlay_color' => [
					'color' => '#000500',
					'transparency' => '0.90',
					'rgba' => 'rgba(0, 5, 0, 0.9)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'full',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'center',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '100',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '100',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '#ededed',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'asymetrical_negative',
				'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,0V150L749,2,0,150V0H1000Z"></path></svg>',
				'size' => '54',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => 'rgb(255, 255, 255)',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'content' => [
					'0' => [
						'type' => 'text',
						'style' => [
							'font' => [
								'font-size' => '17',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '#179299',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '',
								'transparency1' => '1',
								'rgba1' => '',
							],
							'content' => '<p style="text-align: center;">' . __('Podívejte se na 3 dílný video kurz', 'cms_ve') . '</p>',
							'li' => '',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '8',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '50',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p style="text-align: center;">' . __('Jak nastavit facebook reklamu', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '19',
							'max_width' => '560',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'content' => '',
							'video_code' => '',
							'popup_type' => 'image',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'play' => [
								'icon' => 'play1',
								'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/content-icons.svg#icon-play1"></use></svg>',
								'color' => '#f60002',
								'size' => '60',
								'tab' => 'icon',
							],
							'icon_text' => '',
							'icon_text_align' => 'beside',
							'button_text' => __('Spustit video', 'cms_ve'),
							'popupbutton' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'align' => 'center',
							'mw30' => '1',
						],
						'type' => 'video',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '560',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'3' => [
						'style' => [
							'content' => [
								'page' => '',
								'link' => '',
							],
							'layout' => 'button_count',
							'scheme' => 'light',
							'setting' => [
								'share' => '1',
								'is_saved' => '1',
							],
							'align' => 'center',
							'mw30' => '1',
						],
						'type' => 'like',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'4' => [
						'style' => [
							'font' => [
								'font-size' => '',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum risus finibus. </p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '439',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'5' => [
						'style' => [
							'type' => 'smartemailing',
							'content' => [
								'api' => 'se',
							],
							'email' => '',
							'subject' => '',
							'button_text' => '',
							'thx_url' => [
								'page' => '',
								'link' => '',
							],
							'url' => '',
							'form-style' => '1',
							'form-labels' => '1',
							'form-look' => '1',
							'background' => '#eeeeee',
							'corners' => 'sharp',
							'form-font' => [
								'font-size' => '',
							],
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'popup' => '1',
							'popup_type' => 'button',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'popup_text' => __('Chci vědět více', 'cms_ve'),
							'popupbutton' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'big',
								'custom_size' => '18',
							],
							'link_text' => __('Registrovat se', 'cms_ve'),
							'link_font' => [
								'font-size' => '',
								'color' => '',
							],
							'align' => 'center',
							'popup_title' => __('Zadejte svůj e-mail a registrujte se.', 'cms_ve'),
							'textinpopup' => '',
							'mw30' => '1',
						],
						'type' => 'seform',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
];


$page = [
	'page' => [
		'title' => __('Vstupní stránka', 'cms_ve'),
		'slug' => __('vstup', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'page',
			'logo_setting' => 'image',
			'logo' => [
				'position' => '',
				'image' => MW_IMAGE_LIBRARY . 'logo/vaselogo2.png',
				'imageid' => '',
			],
			'logo_size' => '170',
			'logo_text' => __('Název webu', 'cms_ve'),
			'logo_font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '20',
				'color' => '#111111',
			],
			'appearance' => 'type11',
			'menu_style' => '1',
			'menu' => '',
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1',
				'rgba1' => 'rgba(255,255,255,1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'header_padding' => '20',
			'header_height' => '60',
			'menu_font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '15',
				'line-height' => '1.6',
			],
			'menu_color' => '#575757',
			'menu_active_color' => '#158ebf',
			'menu_submenu_bg' => '#ffffff',
			'menu_bg' => '#121212',
			'before_header' => '',
			'border-bottom' => [
				'size' => '',
				'style' => 'solid',
				'color' => '#eeeeee',
				'transparency' => '1',
				'rgba' => '',
			],
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'overlay_color' => [
					'color' => '#158ebf',
					'transparency' => '1',
					'rgba' => '',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'header_width_preset' => '',
			'background_color_fix' => [
				'color1' => '',
				'transparency1' => '1',
				'rgba1' => '',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'logo_color_fix' => '',
			'fixed_menu_color' => '',
			'fixed_menu_active_color' => '',
			'header_padding_fix' => '20',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
