<?php
$temp_layer = [
	'0' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(255, 255, 255, 1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.2',
					'rgba' => 'rgba(0, 0, 0, 0.2)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'iframe',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'full',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'center',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'small',
			'padding_top' => '50',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '50',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-family' => '',
								'weight' => '',
								'font-size' => '30',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'line-height' => '1.2',
								'letter-spacing' => '0',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '3',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p style="text-align: center;">' . __('<span style="color: #ff0000;">Počkejte ještě!</span> Vaše objednávka není kompletní...', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'type' => 'title',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '16',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'style' => [
							'font' => [
								'font-family' => '',
								'weight' => '',
								'font-size' => '25',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'line-height' => '',
							],
							'style' => '1',
							'border' => [
								'size' => '3',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p style="text-align: center;">' . __('Získejte přístup k online kurzu: ', 'cms_ve') . '</p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '35',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'image' => [
								'position' => '50% 50%',
								'image' => '',
								'imageid' => '',
							],
							'thumb_name' => '',
							'upsell-max-width' => '',
							'upsell_image_align' => 'center',
							'img_style' => '1',
							'border' => [
								'size' => '0',
								'style' => 'solid',
								'color' => '#eeeeee',
							],
							'corner' => '',
							'shadow' => '',
							'mw30' => '1',
						],
						'type' => 'upsell_image',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '721',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'3' => [
						'style' => [
							'font' => [
								'font-family' => '',
								'weight' => '',
								'font-size' => '',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'line-height' => '',
							],
							'style' => '1',
							'border' => [
								'size' => '3',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In volutpat volutpat blandit. In hac habitasse platea tortor dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In volutpat volutpat blandit.</p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '25',
							'max_width' => '637',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'4' => [
						'style' => [
							'price_before' => __('Právě teď jen za', 'cms_ve'),
							'price_after' => '',
							'sale_before' => __('Běžná cena:', 'cms_ve'),
							'sale_after' => '',
							'align' => 'center',
							'price_font' => [
								'font-size' => '30',
								'color' => '',
							],
							'price_color' => '#219ed1',
							'sale_font' => [
								'font-size' => '35',
								'color' => '',
							],
							'mw30' => '1',
						],
						'type' => 'upsell_price',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '40',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'5' => [
						'style' => [
							'yes_text' => __('Využít zvýhodněné nabídky', 'cms_ve'),
							'yes_subtext' => __('A přidat tento produkt k objednávce', 'cms_ve'),
							'no_text' => __('Děkuji ale nemám zájem', 'cms_ve'),
							'appearance' => 'under',
							'align' => 'center',
							'button_yes' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '13',
									'background_color' => [
										'color1' => '#424242',
										'transparency1' => '1',
										'rgba1' => 'rgba(66, 66, 66, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '#1a1a1a',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.9',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '#1a1a1a',
									'border_width' => '3',
									'hover_effect' => '',
									'hover_color' => [
										'color1' => '#1a1a1a',
										'transparency1' => '1',
										'rgba1' => 'rgba(26, 26, 26, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '#ffffff',
									'border_hover-color' => '',
								],
								'button_size' => 'big',
								'custom_size' => '18',
							],
							'mw30' => '1',
						],
						'type' => 'upsell',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
];

$config['setting'] = [
	've_header' => ['show' => 'none'],
	've_footer' => ['show' => 'none'],
];
$config['layer'] = base64_encode(serialize($temp_layer));
$config['config'] = [];
