<?php
$temp_layer = [
	'0' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#000500',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(0, 5, 0, 1)',
				'color2' => '',
				'transparency2' => '',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => MW_IMAGE_LIBRARY . 'bg/man_with_comp.jpg',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'color_filter' => '1',
				'overlay_color' => [
					'color' => '#000500',
					'transparency' => '0.90',
					'rgba' => 'rgba(0, 5, 0, 0.9)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'center',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '100',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '100',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '#ededed',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'asymetrical_negative',
				'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,0V150L749,2,0,150V0H1000Z"></path></svg>',
				'size' => '54',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => 'rgb(255, 255, 255)',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-twothree',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-size' => '17',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '0',
								'text-shadow' => 'none',
							],
							'style' => '7',
							'border' => [
								'size' => '2',
								'style' => 'solid',
								'color' => '#72944d',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'left',
							'content' => '<p style="text-align: left;">ZVEME VÁS NA WEBINÁŘ NA TÉMA:</p>',
							'mw30' => '1',
						],
						'type' => 'title',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '6',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '69',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p>' . __('Tajemství cesty zákazníka', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '19',
							'max_width' => '924',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'type' => 'text',
						'style' => [
							'font' => [
								'font-size' => '18',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '#9ea39d',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p>' . __('3 tipy jak postavit cestu zákazníka, která bude vydělávat', 'cms_ve') . '</p>',
							'li' => '41',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '33',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'3' => [
						'style' => [
							'icon' => [
								'icon' => 'calendar',
								'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-calendar"></use></svg>',
								'icon_set' => 'feather',
								'tab' => 'icon',
							],
							'title' => '17.5. ve 12:00',
							'text' => '',
							'link' => [
								'page' => '',
								'link' => '',
							],
							'align' => 'left',
							'style' => 'beside',
							'vertical_align' => 'center',
							'size' => '30',
							'icon_style' => '1',
							'color' => '#ffffff',
							'title_font' => [
								'use-font' => 'title',
								'font-size' => '19',
								'color' => '',
							],
							'font' => [
								'use-font' => 'text',
								'font-size' => '',
								'color' => '',
							],
							'mw30' => '1',
						],
						'type' => 'icon',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '41',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'4' => [
						'style' => [
							'type' => 'smartemailing',
							'content' => [
								'api' => 'se',
							],
							'email' => '',
							'subject' => '',
							'button_text' => '',
							'thx_url' => [
								'page' => '',
								'link' => '',
							],
							'url' => '',
							'form-style' => '1',
							'form-labels' => '1',
							'form-look' => '1',
							'background' => '#eeeeee',
							'corners' => 'sharp',
							'form-font' => [
								'font-size' => '',
							],
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'popup' => '1',
							'popup_type' => 'button',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'popup_text' => __('Registrovat si místo', 'cms_ve'),
							'popupbutton' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'big',
								'custom_size' => '18',
							],
							'link_text' => __('Registrovat se', 'cms_ve'),
							'link_font' => [
								'font-size' => '',
								'color' => '',
							],
							'align' => 'left',
							'popup_title' => __('Zadejte svůj e-mail a registrujte se.', 'cms_ve'),
							'textinpopup' => '',
							'mw30' => '1',
						],
						'type' => 'seform',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'1' => [
				'type' => 'col-three',
				'class' => '',
				'content' => [],
			],
		],
		'type' => 'basic',
	],
	'1' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '100',
				'rgba1' => 'rgba(255, 255, 255, 1)',
				'color2' => '',
				'transparency2' => '100',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => 'center center',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.5',
					'rgba' => 'rgba(0,0,0,0.5)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '70',
				'rgba' => '',
			],
			'video_type' => 'iframe',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '70',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '',
			'arrow_color' => '#fff',
			'content_align' => 'top',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '100',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '100',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-threefive',
				'class' => '',
				'content' => [
					'0' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '30',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#efefef',
								'transparency1' => '1',
								'rgba1' => 'rgba(239, 239, 239, 1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<h2>' . __('Co se na webináři dozvíte?', 'cms_ve') . '</h2>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '20',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'style' => [
							'font' => [
								'font-size' => '16',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p style="text-align: left;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.</p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '42',
							'max_width' => '492',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'type' => 'features',
						'style' => [
							'features' => [
								'0' => [
									'icon' => [
										'icon' => 'monitor',
										'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-monitor"></use></svg>',
										'icon_set' => 'feather',
										'image' => [
											'position' => '',
											'image' => '',
											'imageid' => '',
										],
										'tab' => 'icon',
									],
									'title' => 'Informace č. 1',
									'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'button_text' => __('Více informací →', 'cms_ve'),
									'link' => [
										'page' => '',
										'link' => '',
									],
								],
								'1' => [
									'icon' => [
										'icon' => 'book-open',
										'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-book-open"></use></svg>',
										'icon_set' => 'feather',
										'image' => [
											'position' => '',
											'image' => '',
											'imageid' => '',
										],
										'tab' => 'icon',
									],
									'title' => 'Informace č. 2',
									'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'button_text' => __('Více informací →', 'cms_ve'),
									'link' => [
										'page' => '',
										'link' => '',
									],
								],
								'2' => [
									'icon' => [
										'icon' => 'briefcase',
										'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-briefcase"></use></svg>',
										'icon_set' => 'feather',
										'image' => [
											'position' => '',
											'image' => '',
											'imageid' => '',
										],
										'tab' => 'icon',
									],
									'title' => 'Informace č. 3',
									'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'button_text' => __('Více informací →', 'cms_ve'),
									'link' => [
										'page' => '',
										'link' => '',
									],
								],
							],
							'cols' => 'one',
							'cols_type' => 'smallcols',
							'style' => '2',
							'background_set' => [
								'corner' => '2',
								'shadow' => '1',
								'color' => '#ffffff',
							],
							'icon_size' => '43',
							'background-color' => '#7c9e57',
							'icon_style' => '1',
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#17a2d0',
										'transparency1' => '1',
										'rgba1' => 'rgba(23, 162, 208, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '#ffffff',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.9',
									'font' => [
										'font-family' => 'Open Sans',
										'weight' => '600',
									],
									'border-color' => '#1a1a1a',
									'border_width' => '3',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '#1a1a1a',
										'transparency1' => '1',
										'rgba1' => 'rgba(26, 26, 26, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '#ffffff',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'font' => [
								'use-font' => 'title',
								'font-size' => '23',
								'color' => '',
							],
							'font_text' => [
								'use-font' => 'text',
								'font-size' => '',
								'color' => '',
							],
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'1' => [
				'type' => 'col-twofive',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'background_color' => [
								'color1' => '#7c9e57',
								'transparency1' => '1.00',
								'rgba1' => 'rgba(124, 158, 87, 1)',
							],
							'background_image' => [
								'position' => '50% 50%',
								'image' => '',
								'imageid' => '',
								'pattern' => '0',
								'cover' => '1',
								'overlay_color' => [
									'color' => '#158ebf',
									'transparency' => '1',
									'rgba' => '',
								],
								'repeat' => 'no-repeat',
								'size' => '',
							],
							'border' => [
								'size' => '0',
								'style' => 'solid',
								'color' => '#eeeeee',
							],
							'corner' => '1',
							'padding' => [
								'size' => '40',
								'unit' => 'px',
							],
							'shadow' => '3',
							'text' => 'auto',
							'title' => '',
							'title_bg' => [
								'color1' => '',
								'transparency1' => '1',
								'rgba1' => '',
							],
							'title_border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#000000',
								'transparency' => '0.2',
								'rgba' => 'rgba(0,0,0,0.2)',
							],
							'title-font' => [
								'use-font' => 'title',
								'font-size' => '20',
								'color' => '',
								'align' => 'center',
							],
							'mw30' => '1',
						],
						'type' => 'box',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '550',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
						'content' => [
							'0' => [
								'0' => [
									'style' => [
										'font' => [
											'font-size' => '30',
											'tablet' => [
												'font-size' => '',
											],
											'mobile' => [
												'font-size' => '',
											],
											'color' => '',
											'font-family' => '',
											'weight' => '',
											'line-height' => '1.2',
											'letter-spacing' => '0',
											'text-shadow' => 'none',
										],
										'style' => '1',
										'border' => [
											'size' => '1',
											'style' => 'solid',
											'color' => '#d5d5d5',
										],
										'background-color' => [
											'color1' => '#e8e8e8',
											'transparency1' => '1',
											'rgba1' => 'rgba(232,232,232,1)',
										],
										'decoration-color' => '#158ebf',
										'decoration-padding' => '',
										'align' => 'center',
										'content' => '<p>' . __('Informace o webináři', 'cms_ve') . '</p>',
										'mw30' => '1',
									],
									'type' => 'title',
									'config' => [
										'margin_top' => '',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '800',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
								'1' => [
									'style' => [
										'icon' => [
											'icon' => 'user',
											'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-user"></use></svg>',
											'icon_set' => 'feather',
											'tab' => 'icon',
										],
										'title' => __('Webinářem vás provede', 'cms_ve'),
										'text' => 'David Kirš',
										'link' => [
											'page' => '',
											'link' => '',
										],
										'align' => 'left',
										'style' => 'beside',
										'vertical_align' => 'center',
										'size' => '39',
										'icon_style' => '1',
										'color' => '#c9dbb6',
										'title_font' => [
											'use-font' => 'text',
											'font-size' => '14',
											'color' => '',
										],
										'font' => [
											'use-font' => 'title',
											'font-size' => '18',
											'color' => '',
										],
										'mw30' => '1',
									],
									'type' => 'icon',
									'config' => [
										'margin_top' => '',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
								'2' => [
									'style' => [
										'icon' => [
											'icon' => 'calendar',
											'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-calendar"></use></svg>',
											'icon_set' => 'feather',
											'tab' => 'icon',
										],
										'title' => __('Začátek', 'cms_ve'),
										'text' => '17.5. ve 12:00',
										'link' => [
											'page' => '',
											'link' => '',
										],
										'align' => 'left',
										'style' => 'beside',
										'vertical_align' => 'center',
										'size' => '39',
										'icon_style' => '1',
										'color' => '#c9dbb6',
										'title_font' => [
											'use-font' => 'text',
											'font-size' => '14',
											'color' => '',
										],
										'font' => [
											'use-font' => 'title',
											'font-size' => '18',
											'color' => '',
										],
										'mw30' => '1',
									],
									'type' => 'icon',
									'config' => [
										'margin_top' => '',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
								'3' => [
									'style' => [
										'icon' => [
											'icon' => 'clock',
											'code' => '<svg role="img"><use xlink:href="http://localhost/mioweb/wp-content/themes/MioWeb/library/visualeditor/images/icons/feather/symbol-defs.svg#icon-clock"></use></svg>',
											'icon_set' => 'feather',
											'tab' => 'icon',
										],
										'title' => __('Přibližná délka', 'cms_ve'),
										'text' => 'cca 1h',
										'link' => [
											'page' => '',
											'link' => '',
										],
										'align' => 'left',
										'style' => 'beside',
										'vertical_align' => 'center',
										'size' => '39',
										'icon_style' => '1',
										'color' => '#c9dbb6',
										'title_font' => [
											'use-font' => 'text',
											'font-size' => '14',
											'color' => '',
										],
										'font' => [
											'use-font' => 'title',
											'font-size' => '18',
											'color' => '',
										],
										'mw30' => '1',
									],
									'type' => 'icon',
									'config' => [
										'margin_top' => '',
										'tablet' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'mobile' => [
											'margin_top' => '',
											'margin_bottom' => '',
											'max_width' => '',
										],
										'margin_bottom' => '',
										'max_width' => '',
										'element_align' => 'center',
										'animate' => '',
										'id' => '',
										'class' => '',
										'delay' => '',
									],
								],
							],
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
	'2' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#f7f7f7',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(247, 247, 247, 1)',
				'color2' => '',
				'transparency2' => '1',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.2',
					'rgba' => 'rgba(0, 0, 0, 0.2)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'top',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '50',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '50',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'content' => [
					'0' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '30',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#efefef',
								'transparency1' => '1',
								'rgba1' => 'rgba(239, 239, 239, 1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<h2 style="text-align: center;">' . __('Názory klientů', 'cms_ve') . '</h2>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '60',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'testimonials',
						'style' => [
							'testimonials' => [
								'0' => [
									'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name' => __('Petra', 'cms_ve'),
									'company' => __('Finanční poradce', 'cms_ve'),
									'image' => [
										'position' => '',
										'image' => MW_IMAGE_LIBRARY . 'misc/face-w.jpg',
										'imageid' => '',
									],
								],
								'1' => [
									'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name' => __('Honza', 'cms_ve'),
									'company' => __('Informatik', 'cms_ve'),
									'image' => [
										'position' => '',
										'image' => MW_IMAGE_LIBRARY . 'misc/face-m.jpg',
										'imageid' => '',
									],
								],
							],
							'cols' => 'two',
							'style' => '6',
							'background_set' => [
								'corner' => '',
								'shadow' => '1',
							],
							'image_size' => '2',
							'font' => [
								'font-size' => '',
								'color' => '',
							],
							'font-author' => [
								'font-size' => '',
								'color' => '',
							],
							'miocarousel_setting' => [
								'animation' => 'fade',
								'autoplay' => '1',
								'color_scheme' => '',
								'delay' => '3500',
								'speed' => '1000',
							],
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
	'3' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#000500',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(0, 5, 0, 1)',
				'color2' => '',
				'transparency2' => '',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => MW_IMAGE_LIBRARY . 'bg/man_with_comp.jpg',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'color_filter' => '1',
				'overlay_color' => [
					'color' => '#000500',
					'transparency' => '0.90',
					'rgba' => 'rgba(0, 5, 0, 0.9)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'center',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '100',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '100',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '#ededed',
			],
			'shape_top' => [
				'shape' => 'asymetrical',
				'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M0,0V2L749,150,1000,2V0H0Z"></path></svg>',
				'size' => '51',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => 'rgb(245, 245, 245)',
			],
			'shape_bottom' => [
				'shape' => 'arrow_negative',
				'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,150V0H0V150H351L500,2,649,150h351Z"></path></svg>',
				'size' => '21',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => 'rgb(255, 255, 255)',
				'flip' => '1',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-size' => '40',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '0',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p style="text-align: center;">' . __('Rezervujte si včas své místo na webináři', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'type' => 'title',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '530',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'style' => [
							'font' => [
								'font-size' => '16',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
							],
							'style' => '1',
							'p-background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'content' => '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.</p>',
							'li' => '',
							'mw30' => '1',
						],
						'type' => 'text',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '42',
							'max_width' => '492',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'type' => 'smartemailing',
							'content' => [
								'api' => 'se',
							],
							'email' => '',
							'subject' => '',
							'button_text' => '',
							'thx_url' => [
								'page' => '',
								'link' => '',
							],
							'url' => '',
							'form-style' => '1',
							'form-labels' => '1',
							'form-look' => '1',
							'background' => '#eeeeee',
							'corners' => 'sharp',
							'form-font' => [
								'font-size' => '',
							],
							'button' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'popup' => '1',
							'popup_type' => 'button',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'popup_text' => __('Registrovat si místo', 'cms_ve'),
							'popupbutton' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '9999',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'big',
								'custom_size' => '18',
							],
							'link_text' => __('Registrovat se', 'cms_ve'),
							'link_font' => [
								'font-size' => '',
								'color' => '',
							],
							'align' => 'center',
							'popup_title' => __('Zadejte svůj e-mail a registrujte se.', 'cms_ve'),
							'textinpopup' => '',
							'mw30' => '1',
						],
						'type' => 'seform',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
];

$page = [
	'page' => [
		'title' => __('Vstupní', 'cms_ve'),
		'slug' => __('vstup', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'none',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
