<?php
$temp_layer = [
	'0' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#000500',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(0, 5, 0, 1)',
				'color2' => '',
				'transparency2' => '',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => MW_IMAGE_LIBRARY . 'bg/man_with_comp.jpg',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'color_filter' => '1',
				'overlay_color' => [
					'color' => '#000500',
					'transparency' => '0.90',
					'rgba' => 'rgba(0, 5, 0, 0.9)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'center',
			'text' => 'auto',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '100',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '100',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '0',
				'style' => 'solid',
				'color' => '#ededed',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'asymetrical_negative',
				'code' => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 150" preserveAspectRatio="none"><path d="M1000,0V150L749,2,0,150V0H1000Z"></path></svg>',
				'size' => '54',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => 'rgb(255, 255, 255)',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-size' => '17',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '0',
								'text-shadow' => 'none',
							],
							'style' => '7',
							'border' => [
								'size' => '2',
								'style' => 'solid',
								'color' => '#72944d',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p>ŽIVÉ VYSÍLÁNÍ WEBINÁŘE</p>',
							'mw30' => '1',
						],
						'type' => 'title',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '6',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'1' => [
						'type' => 'title',
						'style' => [
							'font' => [
								'font-size' => '69',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '',
								'letter-spacing' => '',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '1',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<p style="text-align: center;">' . __('Tajemství cesty zákakazníka', 'cms_ve') . '</p>',
							'mw30' => '1',
						],
						'config' => [
							'margin_top' => '0',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '19',
							'max_width' => '924',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'2' => [
						'style' => [
							'countdown_type' => 'date',
							'evergreen_days' => '',
							'evergreen_hours' => '',
							'evergreen_minutes' => '',
							'evergreen_start' => 'enter',
							'content' => [
								'date' => '',
								'hour' => '20',
								'minute' => '0',
							],
							'redirect' => [
								'page' => '',
								'link' => '',
							],
							'style' => '7',
							'text_before' => __('Vysílání začíná za', 'cms_ve'),
							'size' => '24',
							'background-color' => '',
							'font' => [
								'use-font' => 'text',
							],
							'font-text' => [
								'color' => '',
							],
							'mw30' => '1',
						],
						'type' => 'countdown',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
					'3' => [
						'style' => [
							'content' => '',
							'video_code' => '',
							'autoplay' => '1',
							'popup_type' => 'image',
							'image' => [
								'position' => '',
								'image' => '',
								'imageid' => '',
							],
							'play' => [
								'icon' => 'play1',
								'code' => '<svg role="img"><use xlink:href="https://www.mioweb.cz/wp-content/themes/mioweb3/library/visualeditor/images/icons/content-icons.svg#icon-play1"></use></svg>',
								'color' => '#f60002',
								'size' => '60',
								'tab' => 'icon',
							],
							'icon_text' => '',
							'icon_text_align' => 'beside',
							'button_text' => __('Spustit video', 'cms_ve'),
							'popupbutton' => [
								'style' => 'basic',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '8',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'medium',
								'custom_size' => '18',
							],
							'align' => 'center',
							'mw30' => '1',
						],
						'type' => 'video',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
	'1' => [
		'class' => '',
		'style' => [
			'background_color' => [
				'color1' => '#ffffff',
				'transparency1' => '1.00',
				'rgba1' => 'rgba(255, 255, 255, 1)',
				'color2' => '',
				'transparency2' => '',
				'rgba2' => '',
			],
			'background_setting' => 'image',
			'background_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'pattern' => '',
				'tablet' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'mobile' => [
					'position' => '50% 50%',
					'image' => '',
					'imageid' => '',
					'size' => '',
				],
				'cover' => '1',
				'overlay_color' => [
					'color' => '#000000',
					'transparency' => '0.2',
					'rgba' => 'rgba(0, 0, 0, 0.2)',
				],
				'efect' => '',
				'repeat' => 'no-repeat',
				'size' => '',
			],
			'slider_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'video_type' => 'custom',
			'video_url' => '',
			'background_video_mp4' => '',
			'background_video_webm' => '',
			'background_video_ogg' => '',
			'video_image' => [
				'position' => '50% 50%',
				'image' => '',
				'imageid' => '',
				'cover' => '1',
				'size' => '',
			],
			'video_overlay_color' => [
				'color' => '',
				'transparency' => '0.7',
				'rgba' => '',
			],
			'row_height' => 'default',
			'min-height' => '100',
			'arrow_color' => '#fff',
			'content_align' => 'top',
			'text' => 'custom',
			'font' => [
				'font-family' => '',
				'weight' => '',
				'font-size' => '14',
				'color' => '',
			],
			'link_color' => '',
			'type' => 'basic',
			'row_padding' => 'big',
			'padding_top' => '50',
			'tablet' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'mobile' => [
				'padding_top' => '',
				'padding_bottom' => '',
				'padding_left' => [
					'size' => '',
					'unit' => 'px',
				],
				'padding_right' => [
					'size' => '',
					'unit' => 'px',
				],
			],
			'padding_bottom' => '50',
			'padding_left' => [
				'size' => '',
				'unit' => 'px',
			],
			'padding_right' => [
				'size' => '',
				'unit' => 'px',
			],
			'border-top' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'border-bottom' => [
				'size' => '',
				'style' => 'solid',
				'color' => '',
			],
			'shape_top' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'shape_bottom' => [
				'shape' => 'tilt',
				'code' => '<svg viewBox="0 0 1000 100" preserveAspectRatio="none"><path d="M0,6V0h1000v100L0,6z"></path></svg>',
				'size' => '100',
				'tablet' => [
					'size' => '',
				],
				'mobile' => [
					'size' => '',
				],
				'color' => '',
			],
			'margin_top' => '',
			'margin_bottom' => '',
			'css_class' => '',
			'row_anchor' => '',
			'delay' => '',
		],
		'content' => [
			'0' => [
				'type' => 'col-one',
				'class' => '',
				'break' => '1',
				'content' => [
					'0' => [
						'style' => [
							'font' => [
								'font-size' => '40',
								'tablet' => [
									'font-size' => '',
								],
								'mobile' => [
									'font-size' => '',
								],
								'color' => '',
								'font-family' => '',
								'weight' => '',
								'line-height' => '1.2',
								'letter-spacing' => '0',
								'text-shadow' => 'none',
							],
							'style' => '1',
							'border' => [
								'size' => '3',
								'style' => 'solid',
								'color' => '#d5d5d5',
							],
							'background-color' => [
								'color1' => '#e8e8e8',
								'transparency1' => '1',
								'rgba1' => 'rgba(232,232,232,1)',
							],
							'decoration-color' => '#158ebf',
							'decoration-padding' => '',
							'align' => 'center',
							'content' => '<h2 style="text-align: center;">' . __('Své otázky a komentáře pište zde:', 'cms_ve') . '</h2>',
							'mw30' => '1',
						],
						'type' => 'title',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '40',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'1' => [
				'type' => 'col-two',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'content' => [
								'page' => '',
								'link' => '',
							],
							'per_page' => '30',
							'scheme' => 'light',
							'mw30' => '1',
						],
						'type' => 'fcomments',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
			'2' => [
				'type' => 'col-two',
				'class' => '',
				'content' => [
					'0' => [
						'style' => [
							'style' => '3',
							'button' => [
								'style' => '17',
								'custom_setting' => [
									'style' => '1',
									'background_color' => [
										'color1' => '#eb1e47',
										'transparency1' => '1',
										'rgba1' => 'rgba(235, 30, 71, 1)',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'font-color' => '',
									'corner' => '8',
									'height_padding' => '1.1',
									'width_padding' => '1.8',
									'font' => [
										'font-family' => '',
										'weight' => '',
									],
									'border-color' => '',
									'border_width' => '',
									'hover_effect' => 'darker',
									'hover_color' => [
										'color1' => '',
										'transparency1' => '1',
										'rgba1' => '',
										'color2' => '',
										'transparency2' => '1',
										'rgba2' => '',
									],
									'hover_font_color' => '',
									'border_hover-color' => '',
								],
								'button_size' => 'small',
								'custom_size' => '18',
							],
							'mw30' => '1',
						],
						'type' => 'wpcomments',
						'config' => [
							'margin_top' => '',
							'tablet' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'mobile' => [
								'margin_top' => '',
								'margin_bottom' => '',
								'max_width' => '',
							],
							'margin_bottom' => '',
							'max_width' => '',
							'element_align' => 'center',
							'animate' => '',
							'id' => '',
							'class' => '',
							'delay' => '',
						],
					],
				],
			],
		],
		'type' => 'basic',
	],
];

$page = [
	'page' => [
		'title' => __('Vysílání webináře', 'cms_ve'),
		'slug' => __('webinar', 'cms_ve'),
		'theme' => 'page/1/',
	],
	'setting' => [
		've_header' => [
			'show' => 'none',
		],
		've_footer' => [
			'show' => 'none',
		],
		've_appearance' => [],
	],
	'layer' => base64_encode(serialize($temp_layer)),
];
